# Generated by Django 3.0.2 on 2020-02-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200203_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub',
            field=models.CharField(default='', max_length=50),
        ),
    ]
